### ISSUE TITLE
How to run DL

### ISSUE THREAD

**Issue by xuefenfei712** [CshlSiepelLab/arg-selection#2]
Dear authors
I am learning your software recently, follow your instructions, however I can not understand how to run the DL, 
HAPS=$1
FEA_PREF=$2
NO_THR=$3
MODEL=$4

I think HAPS should be the .haps file, and how about others?
Looking forward for your reply, thankyou
Best
Xue

**Comment by xuefenfei712** [comment]
I also tried this:
sh run_model.sh 80 ../genome2args/LCT/LCT_chr2_135500000_137500000 1 ../DL_models/ ./
but got error below
run_model.sh: ligne9: module : commande introuvable
run_model.sh: ligne13: module : commande introuvable
run_model.sh: ligne14: module : commande introuvable
run_model.sh: ligne15: module : commande introuvable
_START_jeu. janv.  6 17:14:18 CET 2022
2022-01-06 17:14:18.821440: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-01-06 17:14:18.821486: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-01-06 17:14:20.412240: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-01-06 17:14:20.412298: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-01-06 17:14:20.412331: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (regine.univ-tlse3.fr): /proc/driver/nvidia/version does not exist
[]
Traceback (most recent call last):
  File "/disk/regine/data2/xuexue/software/arg-selection-master/DL_models/SIA_class_pred.py", line 30, in <module>
    model = tf.keras.models.load_model(MOD_PATH)
  File "/disk/regine/data2/xuexue/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/disk/regine/data2/xuexue/anaconda3/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 118, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: ../DL_models//{saved_model.pbtxt|saved_model.pb}
_EXITSTAT_1

**Comment by ziyimo** [comment]
Hi Xue,

Thanks for reaching out! Apologies for the confusion, the scripts in the `DL_models` directory were out of date and they were meant only to run a pre-trained model. In order to apply SIA to your population of interest, you would need to first simulate training data, infer ARGs and extract features, and finally train a DL model to classify sweeps or infer selection coefficient using the simulated training data. I've updated the repo with some documentations on how to build a SIA model. Please check that out and feel free to reach out if you have any additional questions.

Best,
Mo

**Comment by xuefenfei712** [comment]
Thankyou Mo, and for your reply, do you know what's wrong about the below report:
command:
python recapitation.py 
Error:
Traceback (most recent call last):
  File "recapitation.py", line 4, in <module>
    import msprime
  File "/anaconda3/lib/python3.8/site-packages/msprime/__init__.py", line 36, in <module>
    from msprime.ancestry import (
  File "/anaconda3/lib/python3.8/site-packages/msprime/ancestry.py", line 41, in <module>
    from . import demography as demog
  File "/anaconda3/lib/python3.8/site-packages/msprime/demography.py", line 43, in <module>
    import demes
  File "/disk/regine/data2/xuexue/anaconda3/lib/python3.8/site-packages/demes/__init__.py", line 9, in <module>
    from .demes import (
  File "/anaconda3/lib/python3.8/site-packages/demes/demes.py", line 12, in <module>
    from .load_dump import dumps as demes_dumps
  File "/anaconda3/lib/python3.8/site-packages/demes/load_dump.py", line 10, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel'

**Comment by ziyimo** [comment]
Looks like a dependency issue. Could you try installing `ruamel.yaml`?

**Comment by xuefenfei712** [comment]
Yes it was well installed
Requirement already satisfied: ruamel.yaml in /anaconda3/lib/python3.8/site-packages (0.15.87)
